feat: support dmg format  (#1798)
* feat: add dmg format support

* refactor: permisson file separate

* feat: create hdiutil  command

* feat: dmg file support

* chore: Unarchive function change args

* fix: lint

* fix: format support

* chore: remove debug

* test: add a test case for dmg

* fix: fix aquaSupportFormat to support DMG

* fix: replace os.ReadDir to afero.ReadDir

* fix: wrap errors

* style: fix error messages

* fix: simply use io.Copy

* ci: add workflow to test on macOS

* style: add code comment

* refactor: simplify hdiutil detach

* refactor: change executor to a interface for test

* refactor: replace OpenFile to Create

* refactor: use TempFile to create a temporal file

* test: fix a test

* refactor: use filepath.Join

* fix: create a temporal directory to mount a dmg file

To avoid the conflict.

* fix: log errors for unarchiving dmg files

* refactor: separate exec/dmg.go

* fix: output the error of hdiutil command only when the command failed

* fix: use the third party library to copy files recursively

* https://github.com/aquaproj/aqua/pull/1798#discussion_r1148321839
* https://github.com/otiai10/copy

* fix: set OS to darwin if the file extension is ".dmg"

* fix: fix lint errors

```
Error: pkg/asset/generate.go:106:16: string `darwin` has 3 occurrences, make it a constant (goconst)
				if goos == "darwin" && goarch == "amd64" {
				           ^
```

---------

Co-authored-by: Shunsuke Suzuki <suzuki.shunsuke.1989@gmail.com>